# Generated by Django 5.0.2 on 2024-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_alter_movimentos_data_alter_movimentos_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='descr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
