# Generated by Django 5.0.2 on 2024-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_alter_movimentos_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='descr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
